### ISSUE TITLE
Import is only grabbing the last group of tabs

### ISSUE THREAD

**Issue by vvambo** [keptab/keptab#10]
I used the migrate website to transform ~390 tabs from OneTab. The downloaded .json file is big enough to contain all those links (and I can find them in there).

But when I import the file in the chrome keptab plugin, I only get the oldest group of tabs imported (12 links) so I assume something is wrong with the import functionality.

Keptab v0.4, windows 10, Chrome Version 93.0.4577.63 (64-Bit)
OneTab v1.56

**Comment by mywaiting** [comment]
@vvambo Thanks to report a bug! I will fit this after a moment.

Thanks again!

**Comment by mywaiting** [comment]
@vvambo Fixed at this moment, may you take a try in https://keptab.com/migrate

Thanks!

**Comment by vvambo** [comment]
Wow amazing!
Looks like they're all there and in the proper groups. 

The order is reversed now, but they're there "to have them in case" mostly.
The group names and the favicons are gone, but I wouldn't ask to keep those from migration.
Those 3 points could be future requests, but I imagine there's other stuff with higher priority

I'd consider this bug solved and the issue closed :).

**Comment by mywaiting** [comment]
@vvambo Thanks to leave a message

1. the order is reversed, it is bug, may I  fix this after a moment
2. the group names and favicons are gone, actully, Onetab does not export this in its import/export page, so....I do not know how to make it

to the point 2, even lose the group names, but Keptab with instance search is very helpful, may you take a try

:)

**Comment by mywaiting** [comment]
The order is reversed, now fixed

Now the data with OneTab migrate is operational~~~

**Comment by vvambo** [comment]
This is confusing. I do remember deleting a bunch of favicon entries from the copy/paste export data, because I was suspecting them to create problems - but I can't recreate this.  I must've copy&pasted from the Onetab-page to an editor that would grab Icon, Linktext and link. 

Maybe the importer could grab data from the "share all" instead of "export" in a future version? That could keep the group names and icons, but would mean parsing a website - which might be a slight issue if someone doesnt want their data (links) shared with OneTab and keptab.

But yes, it works like a charm now, I can get the icons back by Opening the groups and storing them back, for example. And while I'm at it; I can name them again. 
The search function is great - if I know what I'm looking for :D
