### ISSUE TITLE
Keptab link at the bottom changes when the group at the bottom is restored

### ISSUE THREAD

**Issue by vvambo** [keptab/keptab#12]
I noticed that the Keptab link (to your website) is changing in a weird way, when I restore the group at the bottom of the page.

![image](https://user-images.githubusercontent.com/61788625/133480227-e13a679b-cc0f-46bd-927c-8ad0e84d2fd1.png)
The link belongs to the first entry of the lowest (bottom) group - before I restored the group.
If I move a few pixels up the keptab-link is still there, but the other other one somehow moved there. 

Nothing big, but maybe its the symptom of a another problem.

This happened on Chrome Version 93.0.4577.82 (Offizieller Build) (64-Bit)

**Comment by mywaiting** [comment]
@vvambo Thanks to leave a bug!

It is amazing that how you can find this!!! In Keptab's code, when you delete a tab or tabs group (restore is another delete ), the tab or tabs group will **fade out** in current page. It means that you can not see it, but it is disappear with opacity 0%, the html block still in current page! but is has deleted in database. When you refresh the all page, it will really really dispaly again.

I may fixed this in next release ( too busy too make more code recently )

Thanks a lot!

**Comment by mywaiting** [comment]
This bug has fixed in Keptab v0.5 that still in developing

I will upload new Keptab to Chrome Webstore ASAP after things done.
