### ISSUE TITLE
Feature Request: Selected Tabs

### ISSUE THREAD

**Issue by johnaweiss** [keptab/keptab#13]
hi
i **LOVE** Keptab! It's one of the **BEST** extensions in the world. 

But, it's missing a _very important feature_ :( 

I want to select **multiple** tabs, and then: 

> "Send **_selected_** tabs to Keptab"

https://www.ghacks.net/2018/08/29/how-to-select-and-move-multiple-chrome-tabs-at-once

Thx!

**Comment by mywaiting** [comment]
@johnaweiss got it! I have take this into the list.

Thanks.

**Comment by mywaiting** [comment]
@johnaweiss Select multiple tabs and send them to Keptab is supported now

You can do it like this: select all the tabs you need and right click Keptab Icon -> ''Send the current tab to Keptab"

I will update new Keptab to Chrome Webstore ASAP

**Comment by johnaweiss** [comment]
Great! Thank you very much!
