### ISSUE TITLE
标签组的星形标记 就是在标签组前面加了个⭐吗，可以置顶标签组吗

### ISSUE THREAD

**Issue by liango2** [keptab/keptab#17]
chrome, 显示keptab页面， 如何才能将指定的标签组置顶呢？标签组前面加了个⭐没有置顶标签组

**Comment by mywaiting** [comment]
新版 Keptab 在页面右侧增加了导航列表/目录导航，凡是加星标而且有命名的标签页组，均会显示在右侧导航列表/目录导航中

请等待更新
