### ISSUE TITLE
建议支持滑动到底部再加载，否则，收藏的页面太多，滚动会很长

### ISSUE THREAD

**Issue by newpost** [keptab/keptab#18]

**Comment by mywaiting** [comment]
这个需求实现起来不难，但是对于 Keptab 来说，这没法完成

如果你有仔细观察过 Keptab 搜索框的工作方式，你就会发现，这搜索框必须以全部加载数据为代价实现的

不过收藏太多条目，确实有滚动过长的烦恼

有打算新增一个实现，将“已命名的标签页组”，整理成一个列表显示在页面右侧，这样已命名的标签页组会在右侧容易查找一点
