### ISSUE TITLE
keptab Failed to execute 'transaction' on 'IDBDatabase' 控制台显示报错，数据丢失了

### ISSUE THREAD

**Issue by Michael-py001** [keptab/keptab#19]
keptab Failed to execute 'transaction' on 'IDBDatabase' 控制台显示报错

在我的私人笔记本上用着一直没事，但是在工作笔记本上遇到过三次了，重新卸载安装3次，现在已经又卸载了，看看作者能不能修复吧，之前保存的数据已经没了，不想再丢了

**Comment by mywaiting** [comment]
Keptab 的数据是保存在浏览器的 IndexedDB 里面的，因为浏览器问题导致 IndexedDB 丢失数据的情况非常少见，至少我在各种情况（包括随机 kill 浏览器进程，保存超过十万条数据等），未能复现任何导致数据丢失的问题

由于 IndexedDB 是当作浏览器缓存保存在磁盘上，可能有些软件会将这些内容当作缓存清理掉

由于 Keptab 目前的用户量很小（不过几千用户），目前暂无后续的云端同步的开发计划。界面上有“数据导出”的按钮，有空可以常点一下，以保证数据不会丢失

对于使用 Keptab 造成你的数据丢失，我深感抱歉

多谢！

**Comment by Zi-Yi-ZHANG** [comment]
> keptab Failed to execute 'transaction' on 'IDBDatabase' 控制台显示报错
> 
> 在我的私人笔记本上用着一直没事，但是在工作笔记本上遇到过三次了，重新卸载安装3次，现在已经又卸载了，看看作者能不能修复吧，之前保存的数据已经没了，不想再丢了

老哥你用啥浏览器，我这 vivaldi 也有这个问题
