### ISSUE TITLE
建议新增标签页组内的网页迁移

### ISSUE THREAD

**Issue by aloha66** [keptab/keptab#2]
首先这个插件是真的赞！！！
我理解标签页组是一个个分类。
场景：我新增了两个标签页组a（1，2，3.html）和b(4，5.html)。我想把4.html放到a里面，现在必须在浏览器中调整好tab的位置顺序才能实现。

建议：加个拖曳或者选择移动标签的功能

ps：请问作者有没有打算开源，让我们学习学习

**Comment by mywaiting** [comment]
@aloha66 你好，Keptab 是有拖拽排序功能的

1. 直接拖动 X个标签页组 的文字到其他标签页组的 Y个标签页 处，可以将整个标签页组（X）与另一个标签组（Y）整组合并的
2. 两个标签页组a（1，2，3.html）和b(4，5.html)，可以直接拖动 4.html 到 a 里面即可
3. 单标签页组a（1，2，3.html），可以直接组内拖动 3.html 到 2.html 上面，排序为 1,3,2.html

注意一下：以上拖动要求标签页在非锁定情况下，锁定（加锁）情况无法拖动

暂时无开源打算，如果你想参考同样的实现，请前往 
- BetterOneTab https://github.com/cnwangjie/better-onetab
- CloudSkyMonster https://github.com/scoful/cloudSkyMonster

**Comment by aloha66** [comment]
@mywaiting 你说的第二点我刚刚试了，的确可以。但我觉得边界范围是不是窄了点？我在拖动到目标的过程中出现了禁止的鼠标图标，所以以为这个功能是没有的。
建议修改：
 .tabs-list .tab {
~~width: fit-content;~~
~~margin-bottom: 8px;~~
padding-bottom: 8px;
}

改完就舒服多了

**Comment by mywaiting** [comment]
@aloha66 我有手动 at 的，不是很清楚 Github 这方面的逻辑，平时参与的 issue 一般有回复会直接出现在我的信息流顶部的

拖动部分确实有不少问题，可用但是不好用，打算把样式啥的重新整理一遍

多谢反馈！

**Comment by mywaiting** [comment]
标签页组拖动的教程/帮助/说明，将会在 Keptab V0.5 版本发布时升级网站帮助文档里得到说明

另，拖动条目时会出现虚线框标识当前拖放放置位置，同样将在准备发布 Keptab V0.5 版本时有调整
