### ISSUE TITLE
vivalid 下使用时不时白屏

### ISSUE THREAD

**Issue by Zi-Yi-ZHANG** [keptab/keptab#20]
环境：Win10，vivaldi 5.1.2567.39 (Stable channel) (64-bit) 

一开始正常，用一段时间后右键 display keptab 的时候会白屏，不知道是 bug 还是插件冲突还是清理缓存什么造成的，大佬有遇到这种情况吗？很好的插件，之前用 OneTab 就怕丢数据提心吊胆的，加油！

![image](https://user-images.githubusercontent.com/46770323/154091095-d4a1d050-3808-4268-8303-260aba545ffa.png)

**Comment by Zi-Yi-ZHANG** [comment]
![image](https://user-images.githubusercontent.com/46770323/154092714-49c292d2-7f9c-4cba-acb0-29194ffcd699.png)
F12 似乎有点线索

**Comment by mywaiting** [comment]
从浏览器的报错来看，应该是 Keptab 整个 indexedDB 数据库全部丢失了

目前尚未更好的办法（除非云端同步）来应对整个 indexedDB 丢失的情况，多数时候，这是清理缓存导致的未知行为，毕竟 indexedDB 是事务执行的，即使浏览器奔溃，也能很好保留数据，这也是我选择 indexedDB 的原因

@Zi-Yi-ZHANG 目前只能删除 Keptab 重新安装才能恢复正常了，至于数据的话，之前要是没有备份，就肯定没有了

实在抱歉，丢失数据，并不是开发 Keptab 的本意
