### ISSUE TITLE
edge浏览器，请问keptab数据存储在哪里？

### ISSUE THREAD

**Issue by whatdoyoudonow** [keptab/keptab#21]
浏览器：Edge
出现问题：keptab打开空白，连顶部的选项栏也没有
解决：删除，重新安装，恢复正常
目前问题：想恢复原本数据，不知道文件存储在哪里，跪求

**Comment by mywaiting** [comment]
实在抱歉造成数据丢失

Keptab 数据使用浏览器内置的 IndexedDB，存放在浏览器内部的 IndexedDB 里面，并没有写入具体的磁盘上的文件。由于 IndexedDB 是具备事务性写入的，理论上不会丢失数据，但如果丢失，那找回的可能性为零

Keptab 界面右上角有导出当前数据的按钮，有空就只能多点几次了~

再次抱歉造成你的数据丢失！
