### ISSUE TITLE
能否开源？

### ISSUE THREAD

**Issue by shoyuf** [keptab/keptab#22]
用户体验方面bug太多了，如果没时间维护的话能否开源让其他人进行更新？

**Comment by wealding** [comment]
虎吕夺食?

**Comment by mywaiting** [comment]
如果感觉用户体验方面bug太多了，可以直接提 issue，我确认一下尽量下个版本修复。

暂时无开源打算，如果你想参考同样的实现，请前往

- BetterOneTab https://github.com/cnwangjie/better-onetab
- CloudSkyMonster https://github.com/scoful/cloudSkyMonster
