### ISSUE TITLE
网站上safari 14.1.2安装地址跳转到了chrome

### ISSUE THREAD

**Issue by dc0453** [keptab/keptab#23]
怎么在safari 14.1.2 上安装呀？
网站上的地址是直接跳转到chrome上的。
appstore上也没查到这个扩展。

**Comment by mywaiting** [comment]
实在抱歉，没有 Appstore 账号，没法上架，还请谅解，正在努力中~

目前是暂时跳转到 chrome webstore， 最新版本的 safari 其实支持 chrome 扩展的，不过需要点技巧~

**Comment by mywaiting** [comment]
最近重写了 Keptab 全部的代码，有尝试上架 Safari 商店（Appstore 商店）

但是开发者账号有点麻烦，暂缓上架，请见谅

此次重写代码后，应该会上架 Firefox 商店
