### ISSUE TITLE
页面显示空白，也无法导出数据

### ISSUE THREAD

**Issue by SinisterD7** [keptab/keptab#24]
DOMException: Failed to execute 'transaction' on 'IDBDatabase': One of the specified object stores was not found.
![image](https://user-images.githubusercontent.com/18538268/179431947-da546cfb-fe80-43a4-92ab-63639e9d5614.png)

**Comment by crysishacker** [comment]
一样啊！为什么！！

**Comment by mywaiting** [comment]
这种情况是 Keptab 背后使用 IndexedDB 丢失数据了，尽管 Chrome 号称 IndexedDB 作为事务数据库不会丢失，但实际使用中，仍然时常有丢失数据的现象，特别清理浏览器缓存，容易造成插件数据丢失

正在紧张开发中的 Keptab v0.5 采用了一个创新的办法，可以绝对保证你的标签页数据安全，敬请期待
