### ISSUE TITLE
Keptab in Edge Data  Loss

### ISSUE THREAD

**Issue by yuzhouStayHungry** [keptab/keptab#25]
Hello, Keptab developers:
  I  found my keptab extension in Edge has lost all the data saved before. Hope this issue will fix asap.
Hava a nice day!

**Comment by dawnmy** [comment]
Had the same issue, when I open Keptab, it does it show anything but a empty page

**Comment by livejq** [comment]
I also encountered this problem, and it is also what I am most afraid of seeing. This is also the case when I used OneTab Plus before.

**Comment by mywaiting** [comment]
Thx to leave the messages

Due to Chrome and it's IndexedDB, Keptab will lose data in some unreachable case. Really, Really sorry for your loss.

I have found some ways to pretect the data in Keptab never lose. The new version will be publised to the Webstore ASAP

**Comment by mywaiting** [comment]
@yuzhouStayHungry @dawnmy @livejq 

New Keptab has released in Chrome Webstore

In the new release, Keptab has new feature which named `recover data`. If you found the data lost in accident, you can go to Keptab options page and click the `recover data` button

every tabs you have stored with Keptab will never lost!

New version is availabel at:

<a href="https://chrome.google.com/webstore/detail/keptab/feodekcipceogpeomnijgmdlmocbggbi">
        <img src="https://user-images.githubusercontent.com/585534/107280622-91a8ea80-6a26-11eb-8d07-77c548b28665.png" alt="Get Keptab for Chrome">
    </a>

or Go to this link: [Get Keptab for Chrome](https://chrome.google.com/webstore/detail/keptab/feodekcipceogpeomnijgmdlmocbggbi)
