### ISSUE TITLE
拖拽移动的时能否做成OneTab那种有个框框显示位置的效果

### ISSUE THREAD

**Issue by PandaFang** [keptab/keptab#26]
拖拽移动某个链接时能否做成OneTab那种有个框框显示位置的效果

**Comment by mywaiting** [comment]
拖动时候出现虚线框标识拖动位置，在准备发布的 Keptab v0.5 有 fixed 此功能

多谢反馈！

**Comment by mywaiting** [comment]
新版本的 Keptab 已经发布到 Chrome Webstore，目前版本 v1.0

新版本已经完整实现了 `drop'n'drop` 拖放/拖拽时候会出现 `placeholder` 用于指示拖放位置

请点击下面的图标前往商店更新，或者等浏览器自动推送更新

<a href="https://chrome.google.com/webstore/detail/keptab/feodekcipceogpeomnijgmdlmocbggbi">
        <img src="https://user-images.githubusercontent.com/585534/107280622-91a8ea80-6a26-11eb-8d07-77c548b28665.png" alt="Get Keptab for Chrome">
    </a>

**Comment by PandaFang** [comment]
> 

好的，辛苦了。
Edge 那边会更新吗？

**Comment by PandaFang** [comment]
> 新版本的 Keptab 已经发布到 Chrome Webstore，目前版本 v1.0
> 
> 新版本已经完整实现了 `drop'n'drop` 拖放/拖拽时候会出现 `placeholder` 用于指示拖放位置
> 
> 请点击下面的图标前往商店更新，或者等浏览器自动推送更新
> 
> [ ![Get Keptab for Chrome](https://user-images.githubusercontent.com/585534/107280622-91a8ea80-6a26-11eb-8d07-77c548b28665.png) ](https://chrome.google.com/webstore/detail/keptab/feodekcipceogpeomnijgmdlmocbggbi)

好的，辛苦了。
Edge 那边会更新吗？

**Comment by mywaiting** [comment]
@PandaFang 你好，Edge Add-ons 上周就已经上传更新包了，然而一直都是审核中，我也没啥办法，只能干等审核了

ps. 微软的团队审核等过最长的一次是记得好像是两个星期，凉拌，只能干等
