### ISSUE TITLE
Keptab Missing from Chrome Store

### ISSUE THREAD

**Issue by johnaweiss** [keptab/keptab#27]
It's not there

https://keptab.com/chrome

https://chrome.google.com/webstore/detail/keptab/feodekcipceogpeomnijgmdlmocbggbi

Also missing from Opera

https://addons.opera.com/en/extensions/details/keptab/

Best extension!

**Comment by mywaiting** [comment]
Thx to leave this message.

Due to Chrome Webstore policy change and Keptab use Manifest v2. Webstore has noticed me that they deleted Keptab from the store

I will upload Keptab v0.5(new version) into Webstore ASAP

And more, opera addons has rejected my upload and I have no idea what they happen.

**Comment by mywaiting** [comment]
New Keptab has released in Chrome Webstore

<a href="https://chrome.google.com/webstore/detail/keptab/feodekcipceogpeomnijgmdlmocbggbi">
        <img src="https://user-images.githubusercontent.com/585534/107280622-91a8ea80-6a26-11eb-8d07-77c548b28665.png" alt="Get Keptab for Chrome">
    </a>

or Go to this link: [Get Keptab for Chrome](https://chrome.google.com/webstore/detail/keptab/feodekcipceogpeomnijgmdlmocbggbi)

**Comment by johnaweiss** [comment]
Hi, Keptab is missing from Chrome store again.
