### ISSUE TITLE
It can not be found in chrome web store now!

### ISSUE THREAD

**Issue by seanxuu** [keptab/keptab#28]
What happened there? How should I download the newest version of this extension?

**Comment by mywaiting** [comment]
I have uploaded the new version Keptab into Chrome Webstore for few days. Now is pending to review

I have no idea with that. and so, just waiting

**Comment by mywaiting** [comment]
New Keptab has released in Chrome Webstore

<a href="https://chrome.google.com/webstore/detail/keptab/feodekcipceogpeomnijgmdlmocbggbi">
        <img src="https://user-images.githubusercontent.com/585534/107280622-91a8ea80-6a26-11eb-8d07-77c548b28665.png" alt="Get Keptab for Chrome">
    </a>

or Go to this link: [Get Keptab for Chrome](https://chrome.google.com/webstore/detail/keptab/feodekcipceogpeomnijgmdlmocbggbi)
