### ISSUE TITLE
Support for OneTab tab list format

### ISSUE THREAD

**Issue by mcint** [keptab/keptab#29]
Thank you for reimplementing OneTab to address growing issues.

I'm quite fond of the simplicity & compactness of OneTab's data format. Would you be willing to implement, or open to PRs implementing, exporting and importing of tabs in this format in addition to the rich json representation?
```
https://keptab.com/ | Keptab
https://chrome.google.com/webstore/detail/keptab/feodekcipceogpeomnijgmdlmocbggbi | Keptab - Chrome Web Store
```

**Comment by mywaiting** [comment]
I think JSON format is more perfect for exporting and importing data. But I have got some feedback for the data format as your issue.

I prepare to make a tool page on keptab.com, free to use for OneTab users/all users. And more, I will place some tips on exporting and importing button.

This feature maybe online on next some days.

And more, if you need to export just **one tabs group links**, just click the "more...." and selected **"Copy links to clipboard"**, this feature works like OneTabs and the format like OneTab data format toooooo

Thanks

**Comment by mywaiting** [comment]
🎉🎉 Now support OneTab list format!

Please goto https://keptab.com/migrate/ and paste the Keptab exported JSON content to the textarea in **Convert Keptab Exporting Data**

Just click **Copy to Clipboard**, enjoy it @mcint
