### ISSUE TITLE
chrome点击右上角的本插件会导致chrome闪退

### ISSUE THREAD

**Issue by aloha66** [keptab/keptab#3]
曾经试过几次会闪退。

还有一个问题，也是暂时没办法复现：用着用着说本插件已损坏，然后修复完发现数据没了(ps：作为前端小菜鸡，看来我也要了解一下indexedDB了)

chrome版本：91.0.4472.106
系统win10

**Comment by mywaiting** [comment]
确实是存在闪退的可能，已经在新版本里修复，稍后将会更新新版本

chrome 下我没有遇到过数据丢失情况，各种折腾下都没有复现过数据丢失情况。除非是直接清理浏览器的数据，360有时候会干这事情，原因不明

如果发现数据异常，可以尝试一下在 Keptab 页面按 F12 打开 开发者工具，然后找到 应用程序 -> 存储 -> IndexedDB
-> keptab -> lists 看看里面还有没有数据

1. 如果有数据的话，那去设置页面点击导出数据应该是有导出的
2. 如果没有数据的话，那数据应该是丢失了

如果实在造成丢失数据，我深感抱歉

针对你的情况，我在接下来的版本更新中：
1. 我会把 Keptab 的数据导出放到 Keptab 首页的右上角，方便大家随时点导出（这个已经完成~~~）
2. 在写 Keptab 的多浏览器数据同步的实现了，简单说就是一个云备份的服务吧，还需要点时间


最后最后，对于造成你数据丢失的情况，我深感抱歉！希望 Keptab 不会影响到你的好心情！

**Comment by aloha66** [comment]
我这次数据丢失也是小问题，都是测试内容。chrome提示是keptab插件损坏了，我当时也打不开，只能重新安装。我用过keptab之后觉得真的很棒，已经安利了几个朋友使用

**Comment by mywaiting** [comment]
@aloha66 已经完成这么一个功能增加：

1. 把 Keptab 的数据导出放到 Keptab 首页的右上角，方便大家随时点导出（这个已经完成~~~）

稍后将会更新到各大浏览器商店~

虽然很难复现插件损坏的情况，但是还挺好奇啥原因会导致插件损坏了，毕竟我平时各种搞强度使用，好像没啥事，当然了，大家的电脑环境、系统版本啥的可能不同

我挺想找到导致插件损坏的原因的~~

多谢反馈！
