### ISSUE TITLE
Feature Request: Remonve duplicate URLs from old tab lists and add them as new items to the latest /topest tab list.

### ISSUE THREAD

**Issue by iBoostAI** [keptab/keptab#32]
I really want the following new feature: 
Remonve duplicate URLs from old tab list blocks and add them as new items to the latest /topest tab list block.

**Comment by mywaiting** [comment]
You can do it just simply **restore** the tab groups and then **store** them into Keptab again. 

But if you have lots of tab groups and need to repeat that actions, you may need to re-constructed your exported json content from Keptab and re-import into Keptab.

**Comment by iBoostAI** [comment]
It seems you haven't really understood my meaning.
