### ISSUE TITLE
按日期进行分组

### ISSUE THREAD

**Issue by FOVLRui** [keptab/keptab#33]
能否增加按日期分组的功能，同一天的默认放在一个分组里

**Comment by mywaiting** [comment]
这个实现貌似很难处理好，如果需要同一天的放在一个分组里，那需要按窗口保存标签页的小伙伴可能要爆炸了

Keptab 支持拖动功能的，建议保存分组后，直接拖动 A 分组的 N个标签页 处到 B 分组就能完成两个分组合并

建议自行合并分组
