### ISSUE TITLE
2023-10-4 Keptab 显示空白页，无法使用

### ISSUE THREAD

**Issue by 1c7** [keptab/keptab#34]
<img width="1352" alt="image" src="https://github.com/keptab/keptab/assets/1804755/80b8bda9-b866-44e8-997c-734bd1faa341">

**Comment by 1c7** [comment]
<img width="1352" alt="image" src="https://github.com/keptab/keptab/assets/1804755/55e7f4f8-e52b-4f17-8fd2-1296ab736f56">
<img width="1352" alt="image" src="https://github.com/keptab/keptab/assets/1804755/81c188ed-f641-462b-ad58-dd6c9fc5821e">

**Comment by mywaiting** [comment]
应该是数据丢失了，去截图里的第二个页面（选项页面），右侧，点击数据灾难导出，导出数据

导出数据后，重新安装 Keptab 后，再去选项页面导入第一步已经导出的数据

Keptab 使用浏览器的 IndexedDB 数据库保存数据，一旦这个被清理（各种原因可能被清理），数据会丢失

新版 Keptab 通过使用浏览器历史记录保存了数据，可以按照上面的步骤找回丢失的数据

**Comment by 1c7** [comment]
感谢回复～

**Comment by 1c7** [comment]
## 数据灾难导出得到空内容
<img width="273" alt="image" src="https://github.com/keptab/keptab/assets/1804755/82222f35-cf7c-4a96-ba06-587d621e3632">
<img width="896" alt="image" src="https://github.com/keptab/keptab/assets/1804755/a8162289-126c-4061-9ca0-b565f7d87304">


## 可能是我之前清理数据导致的？
<img width="752" alt="image" src="https://github.com/keptab/keptab/assets/1804755/0e6daf0e-fdd8-4224-9eb2-ae5ab968073d">



不管了，反正修复不了就算了，数据丢就丢了，总之感谢回复

**Comment by mywaiting** [comment]
@1c7 数据灾难导出是v2.0 版本更新的功能，可能是在版本更新后，你没有使用过 Keptab 保存过标签页

嗯嗯，实在抱歉~~
