### ISSUE TITLE
无法保存本地文件

### ISSUE THREAD

**Issue by 1Dtfc** [keptab/keptab#5]
如题。
想要将本地的PDF文件和网页一起保存，但最后只显示网页不显示本地文件。
希望加上这个功能。

**Comment by mywaiting** [comment]
@1Dtfc  这么细的细节还真有人会用到......

这样的，Keptab 针对 `'about:', 'chrome:', 'file:'` 开头的 URL ，会选择直接忽略这些 URL ~

一般来说这样的 URL 开头都是特殊协议，比如 `file:///C:/abc.txt` 这样的对应着本地路径

选择跳过不保存这些特殊协议，有很多考虑，其中之一就是隐私问题，Keptab 稍候会加上标签页组同步/分享的功能，直接记录本地路径是非常过分的隐私，这个坑还是留着不踩了，尽管支持这个也就是一行代码的事情

请见谅。多谢！
