### ISSUE TITLE
支持oneTab的数据导入到本插件吗？

### ISSUE THREAD

**Issue by newpost** [keptab/keptab#6]
是否有支持计划？

**Comment by mywaiting** [comment]
@newpost 实在抱歉，忘记将链接写到 Keptab Options 配置页面里面了，有支持的

不想在插件里搞一个单独的页面，我把这个功能丢官网去了，也就是十几行 JS 代码的事情

传送门 https://keptab.com/migrate 

直接粘贴 OneTab 导出的文本，粘贴到链接里面的文本框，点击转换即可，会自动下载为 Keptab 用的 json 数据，直接导入 Keptab 即可
