### ISSUE TITLE
添加单个标签页时Keptab不会动态地刷新, 而在点击在Keptab中的标签页并且删除该标签页时却有效

### ISSUE THREAD

**Issue by Hikar1i** [keptab/keptab#8]
添加单个标签页时Keptab不会动态地刷新, 而在点击在Keptab中的标签页并且删除该标签页时却有效, 并且不论在添加或删除时顶部的总共N个标签页的数字都不会改变, 都需要在手动刷新后才能改变

**Comment by mywaiting** [comment]
@Hikar1i 你好，感谢反馈BUG

Keptab 在添加单个/多个标签页不会自动刷新已经打开的 Keptab 首页，这是一个已知的 BUG，修复需要点时间吧，这个问题确实拖了很久了，实在不好意思

至于添加和删除标签页组顶部 N 个标签不会刷新的问题，确实是个 BUG，下个版本修复

多谢你的反馈！

**Comment by mywaiting** [comment]
@Hikar1i 你好，感谢你的反馈

Keptab 经过本轮代码重写和更新之后，增加/删除标签页会自动更新顶部共 N 个标签页的数字
