### ISSUE TITLE
不能连续删除

### ISSUE THREAD

**Issue by Rhilip** [keptab/keptab#9]
使用版本 : 0.4 ，通过Edge商店安装

在删除已有标签页时，需要先移动到标题位置，然后才会出现删除按钮。
而且在光标左移的过程中，很容易失焦导致删除按钮被隐藏。

队这种设计表示很不理解。
并导致 保存的标签页并不能连续删除。（我往往需要删除其中的一些，而不是整个选项卡组删除）

希望这个设计能进行更改，或者提供相关配置选项。

![output](https://user-images.githubusercontent.com/13842140/131153970-169f5220-f3a0-4ed2-9f87-bde2095b058d.gif)

**Comment by mywaiting** [comment]
@Rhilip 你好，感谢反馈问题

从当初设计的初心来说，确实是没有打算提供太顺滑的删除的实现。现在的删除逻辑是标签页组没有加锁情况下，且鼠标放到具体条目上，左边才会出现删除的按钮，因为没有提供删除确认的对话框，**先移动到标题位置，然后才会出现删除按钮，而且在光标左移的过程中，很容易失焦导致删除按钮被隐藏**，这样的做法，勉为其难就当作是我提供删除确认的方式吧

因为如果不是一心想要删除，那肯定点不到那个微小的叉叉

另外，如果需要连续删除同一个标签页组的条目，鼠标定住在第一个叉出现的位置，然后不断点击左键即可顺序删除。我测试了 Chrome/Edge 均是如此，你可以试试看

造成使用的不便，还是请见谅～

**Comment by Rhilip** [comment]
> 另外，如果需要连续删除同一个标签页组的条目，鼠标定住在第一个叉出现的位置，然后不断点击左键即可顺序删除。我测试了 Chrome/Edge 均是如此，你可以试试看

感谢告知该方法。已经测试成功。

另还请作者看看，能否将删除操作做成多选框形式，这样就可以同时勾选然后统一删除。我觉得这是一种比较好的替代方式。（当初我用 onetab 也是有这种想法）

如果短期内无这个可能，可以直接关闭issue了。
再次感谢。

**Comment by mywaiting** [comment]
@Rhilip 前面提及过，删除这个操作对于 Keptab 来说，频次应该是比较低的操作之一，只是提供一下这个功能，我并不打算增加太便捷的删除操作，算是跟 Keptab 作为保存工具的定位相适应吧，我想法中，保存到 Keptab 的标签页一般都不会怎么去重新编辑/删除/调整顺序，不过也不排除有强迫症的完美主义的同学吧

仍然感谢反馈使用上的问题！
